AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/**/*
    - test/fixtures/**/*
    - tmp/**/*

# -- Layout --------------------------------------------------------------------
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

# -- Metrics -------------------------------------------------------------------
Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# -- Naming --------------------------------------------------------------------
Naming/MethodParameterName:
  Enabled: false

# -- Style ---------------------------------------------------------------------
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/Lambda:
  EnforcedStyle: literal

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false