name: "Coveralls"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coveralls:
    strategy:
      matrix:
        ruby-version:
          - "3.2"
        rails-version:
          - "7.0"
        continue-on-error: [false]
    name: ${{ format('Coverage (Ruby {0}, Rails {1})', matrix.ruby-version, matrix.rails-version) }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.continue-on-error }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.rails-version }}.gemfile
      RAILS_ENV: test
      COVERALLS_REPO_TOKEN: dYKwmmNBzkQR6veagOrHJLet5gsK1E486

    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Set up Test DB
        run: bin/rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bin/rake test

