name: "Rails CI"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_lint_audit:
    strategy:
      matrix:
        ruby-version:
          - "2.7"
          - "3.1"
          - "3.2"
        rails-version:
          - "6.1"
          - "7.0"
        continue-on-error: [false]
    name: ${{ format('Tests (Ruby {0}, Rails {1})', matrix.ruby-version, matrix.rails-version) }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.continue-on-error }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.rails-version }}.gemfile
      RAILS_ENV: test
      COVERALLS_REPO_TOKEN: dYKwmmNBzkQR6veagOrHJLet5gsK1E486

    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Set up Test DB
        run: bin/rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bin/rake test

      - name: Ruby Lint
        run: bin/bundle exec rubocop --parallel

      - name: Security audit application code
        run: bin/bundle exec brakeman -q -w3

      - name: Security audit dependencies
        run: bin/bundle exec bundler-audit --update --gemfile-lock gemfiles/${{ matrix.rails-version }}.gemfile.lock
